version: "3.7"

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 9098:80
        links:
            - fpm
        depends_on:
            - fpm
            - db
            - nodejs
        volumes:
            - ./:/var/www/laravel-docker
    nodejs:
        image: node
        container_name: nodemode
        working_dir: /var/www/laravel-docker
        volumes:
            - ./:/var/www/laravel-docker
        command: bash -c "npm install && npm run dev"
        depends_on:
            - fpm
    fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - db
    db:
        image: mysql
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
