version: "3.7"

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 9098:80
        links:
            - fpm
        volumes:
            - ./:/var/www/laravel-docker
    fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - mysql
    mysql:
        image: mysql
        container_name: database
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
